run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    run:
      timeout: 5m
      tests: true

    linters:
      enable:
        - govet
        - staticcheck
        - errcheck
        - gofmt
        - goimports
        - gosimple
        - unused
        - ineffassign
        - typecheck
        - bodyclose

    issues:
      exclude-use-default: false

    # Note: removed custom errcheck.ignore setting because some golangci-lint
    # versions expect a string; keep default behavior to avoid config errors.
    linters-settings: {}

    exclude:
      - _gen.go