run:
  timeout: 5m
  tests: true

linters:
  # Start with a conservative, small set of linters to reduce noise.
  # We can expand this later once the codebase is clean.
  enable:
    - govet
    - staticcheck
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - unused
    - ineffassign
    - typecheck
    - bodyclose

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - errcheck
      # ignore errcheck findings that match these simple function names
      text: "Close"
    - linters:
        - errcheck
      text: "Write"
    - linters:
        - errcheck
      text: "Flush"

linters-settings: {}

exclude:
  - _gen.go