# Codecov configuration file for Flow
# See docs/codecov.md for setup instructions (token & GitHub secret)

comment:
  # Controls comment verbosity on PRs; set to 'minimal' or 'off' as you prefer
  layout: default

coverage:
  status:
    project:
      default:
        # Desired minimum project coverage (adjust later)
        target: 80
    patch:
      default:
        # Don't fail PRs for small changes unless you raise this threshold
        target: 0

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no

ignore:
  - examples/*
