package generator

var controllerTmpl = `// Code generated by flow generate; DO NOT EDIT.
package {{.Package}}

import (
    "net/http"
    flow "github.com/dministrator/flow/pkg/flow"
)

// {{.Controller}} is a simple controller generated by Flow.
type {{.Controller}} struct{ *flow.Controller }

func New{{.Controller}}(app *flow.App) *{{.Controller}} {
    return &{{.Controller}}{Controller: flow.NewController(app)}
}

func (c *{{.Controller}}) Index(ctx *flow.Context) {
    ctx.JSON(200, map[string]string{"action": "index"})
}

func (c *{{.Controller}}) Show(ctx *flow.Context) {
    id := ctx.Param("id")
    ctx.JSON(200, map[string]string{"id": id})
}
`

// removed unused generated model template (bunModelTmpl is used instead)

// bunModelTmpl is a model template that includes bun struct tags which are
// friendly to the bun ORM adapter. Generators will use this when bun is the
// chosen adapter.
var bunModelTmpl = `// Code generated by flow generate; DO NOT EDIT.
package {{.Package}}

import (
    "context"
    "github.com/dministrator/flow/pkg/flow"
{{.ExtraImports}}
)

// {{.Model}} is a generated model using bun struct tags.
type {{.Model}} struct {
    flow.Model
{{.FieldsCode}}
}

// Save persists the model. It inserts when ID==0 or updates otherwise.
func (m *{{.Model}}) Save(ctx context.Context, app *flow.App) error {
    if m.ID == 0 {
        return flow.Insert(ctx, app, m)
    }
    return flow.Update(ctx, app, m)
}

// Delete removes the model from the database.
func (m *{{.Model}}) Delete(ctx context.Context, app *flow.App) error {
    return flow.Delete(ctx, app, m)
}
`

var migrationUpTmpl = `-- Migration: {{.Timestamp}}_create_{{.Table}}.up.sql
-- Generated by flow
CREATE TABLE IF NOT EXISTS {{.Table}} (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
{{.Columns}}
);
{{.ExtrasUp}}
`

var migrationDownTmpl = `-- Migration: {{.Timestamp}}_create_{{.Table}}.down.sql
-- Generated by flow
{{.ExtrasDown}}
DROP TABLE IF EXISTS {{.Table}};
`

var viewIndexTmpl = `<h1>{{.Title}} index</h1>
<ul>
{{range .Items}}  <li>{{.}}</li>
{{end}}</ul>`

var viewShowTmpl = `<h1>{{.Title}} show</h1>
<p>ID: {{.ID}}</p>`

var viewNewTmpl = `<h1>New {{.Title}}</h1>
<form method="post" action="">
    <!-- TODO: fields -->
    <button type="submit">Create</button>
</form>`

var viewEditTmpl = `<h1>Edit {{.Title}}</h1>
<form method="post" action="">
    <!-- TODO: fields -->
    <button type="submit">Save</button>
</form>`
