package generator

var controllerTmpl = `// Code generated by flow generate; DO NOT EDIT.
package {{.Package}}

import (
    "net/http"
    flow "github.com/dministrator/flow/pkg/flow"
)

// {{.Controller}} is a simple controller generated by Flow.
type {{.Controller}} struct{ *flow.Controller }

func New{{.Controller}}(app *flow.App) *{{.Controller}} {
    return &{{.Controller}}{Controller: flow.NewController(app)}
}

func (c *{{.Controller}}) Index(ctx *flow.Context) {
    ctx.JSON(200, map[string]string{"action": "index"})
}

func (c *{{.Controller}}) Show(ctx *flow.Context) {
    id := ctx.Param("id")
    ctx.JSON(200, map[string]string{"id": id})
}
`

var modelTmpl = `// Code generated by flow generate; DO NOT EDIT.
package {{.Package}}

import (
    "github.com/dministrator/flow/pkg/flow"
)

// {{.Model}} is a generated model (skeleton).
type {{.Model}} struct {
    flow.Model
    // TODO: add fields
}
`

// bunModelTmpl is a model template that includes bun struct tags which are
// friendly to the bun ORM adapter. Generators will use this when bun is the
// chosen adapter.
var bunModelTmpl = `// Code generated by flow generate; DO NOT EDIT.
package {{.Package}}

import (
    "github.com/dministrator/flow/pkg/flow"
{{.ExtraImports}}
)

// {{.Model}} is a generated model using bun struct tags.
type {{.Model}} struct {
    flow.Model
{{.FieldsCode}}
}
`

var migrationUpTmpl = `-- Migration: {{.Timestamp}}_create_{{.Table}}.up.sql
-- Generated by flow
CREATE TABLE IF NOT EXISTS {{.Table}} (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
{{.Columns}}
);
`

var migrationDownTmpl = `-- Migration: {{.Timestamp}}_create_{{.Table}}.down.sql
-- Generated by flow
DROP TABLE IF EXISTS {{.Table}};
`

var viewIndexTmpl = `<h1>{{.Title}} index</h1>
<ul>
{{range .Items}}  <li>{{.}}</li>
{{end}}</ul>`

var viewShowTmpl = `<h1>{{.Title}} show</h1>
<p>ID: {{.ID}}</p>`

var viewNewTmpl = `<h1>New {{.Title}}</h1>
<form method="post" action="">
    <!-- TODO: fields -->
    <button type="submit">Create</button>
</form>`

var viewEditTmpl = `<h1>Edit {{.Title}}</h1>
<form method="post" action="">
    <!-- TODO: fields -->
    <button type="submit">Save</button>
</form>`

